In [1]:
import numpy as np
import pandas as pd
import unicodecsv
import matplotlib.pyplot as plt

dir = "../"


records = pd.read_csv(dir+"globalterrorismdb_0617dist.csv",encoding='ISO-8859-1',usecols=[ 1,8, 13, 14, 100,103])

print len(records)
print records.head()

170350
   iyear         country_txt   latitude   longitude  nkillter  nwoundte
0   1970  Dominican Republic  18.456792  -69.951164       NaN       NaN
1   1970              Mexico  19.432608  -99.133207       NaN       NaN
2   1970         Philippines  15.478598  120.599741       NaN       NaN
3   1970              Greece  37.983773   23.728157       NaN       NaN
4   1970               Japan  33.580412  130.396361       NaN       NaN

In [45]:
lat = records.groupby(['iyear','country_txt']).agg('mean')['latitude'].reset_index()
lon = records.groupby(['iyear','country_txt']).agg('mean')['longitude'].reset_index()

kill = records.groupby(['iyear','country_txt']).agg('sum')['nkillter'].reset_index()
wound = records.groupby(['iyear','country_txt']).agg('sum')['nwoundte'].reset_index()
counts = records.groupby(['iyear','country_txt']).size().rename('counts').reset_index()

tt =lat.merge(lon, on=['iyear','country_txt'])
tt = tt.merge(kill, on=['iyear','country_txt'])
tt = tt.merge(wound, on=['iyear','country_txt'])
tt = tt.merge(counts, on=['iyear','country_txt'])


tt['severe'] =  tt.fillna(0)['nkillter']+tt.fillna(0)['nwoundte']
print len(tt)
tt = tt.sort_values(by=['iyear', 'severe'], ascending=[1, 0])

tt.to_csv("terror.csv")

3648
      iyear         country_txt   latitude   longitude  nkillter  nwoundte  \
29     1970      United Kingdom  54.103960   -5.251001       6.0       NaN
30     1970       United States  38.512780  -93.082479       4.0       1.0
11     1970              Greece  37.980711   23.720484       2.0       0.0
31     1970             Uruguay -34.891151  -56.187214       2.0       NaN
15     1970              Israel  32.085688   34.783684       1.0       0.0
0      1970           Argentina -33.315261  -59.442761       NaN       NaN
1      1970           Australia -37.813187  144.962980       NaN       NaN
2      1970             Belgium  50.850335    4.351685       NaN       NaN
3      1970             Bolivia        NaN         NaN       NaN       NaN
4      1970              Brazil -21.726279  -43.719788       0.0       0.0
5      1970              Canada  46.803137  -71.241298       NaN       NaN
6      1970            Colombia   5.059097  -75.505960       NaN       NaN
7      1970  Dominican Republic  18.456792  -69.951164       NaN       NaN
8      1970  East Germany (GDR)  52.516667   13.400000       NaN       NaN
9      1970               Egypt  31.198056   29.919167       NaN       NaN
10     1970            Ethiopia        NaN         NaN       NaN       NaN
12     1970           Guatemala  14.624422  -90.532880       NaN       NaN
13     1970                Iran  35.696442   51.422974       NaN       NaN
14     1970             Ireland  53.344104   -6.267494       NaN       NaN
16     1970               Italy  41.890520   12.494249       0.0       0.0
17     1970               Japan  33.580412  130.396361       0.0       0.0
18     1970              Jordan  31.903614   35.840766       NaN       NaN
19     1970             Lebanon  33.888629   35.495479       NaN       NaN
20     1970              Mexico  19.432608  -99.133207       NaN       NaN
21     1970         Netherlands  52.370216    4.895168       0.0       0.0
22     1970           Nicaragua  12.136389  -86.251389       NaN       NaN
23     1970            Pakistan  24.893379   67.028061       NaN       NaN
24     1970            Paraguay -25.282773  -57.635610       NaN       NaN
25     1970         Philippines  14.625092  120.984991       NaN       NaN
26     1970               Spain  43.019561   -2.229568       NaN       NaN
...     ...                 ...        ...         ...       ...       ...
3577   2016              Guyana   6.800481  -58.167907       0.0       0.0
3579   2016            Honduras  15.657635  -85.996848       0.0       0.0
3580   2016             Hungary  47.505298   19.063486       0.0       0.0
3585   2016             Ireland  53.200832   -7.276891       0.0       0.0
3589   2016               Japan  35.613610  139.213193       0.0       0.0
3593   2016              Kosovo  42.663504   21.009057       0.0       0.0
3596   2016                Laos  19.277632  102.517098       0.0       0.0
3599   2016          Madagascar -18.885671   47.508818       0.0       0.0
3601   2016            Maldives   3.607756   72.955585       0.0       0.0
3603   2016              Mexico  22.683194 -101.474017       0.0       0.0
3604   2016             Moldova  47.010453   28.863810       0.0       0.0
3608   2016         Netherlands  52.045807    5.608310       0.0       0.0
3609   2016         New Zealand -37.957009  176.986756       0.0       0.0
3613   2016              Panama   7.901095  -77.514980       0.0       0.0
3614   2016            Paraguay -23.332154  -56.609798       0.0       0.0
3615   2016                Peru -13.452190  -73.780946       0.0       0.0
3617   2016              Poland  51.644493   18.991439       0.0       0.0
3620   2016              Rwanda  -1.572625   29.375760       0.0       0.0
3622   2016        Sierra Leone   8.363261  -13.079800       0.0       0.0
3623   2016     Slovak Republic  48.156876   17.113686       0.0       0.0
3625   2016        South Africa -29.682583   28.741406       0.0       0.0
3626   2016         South Korea  36.119485  128.344573       0.0       0.0
3628   2016               Spain  41.787314   -2.468194       0.0       0.0
3629   2016           Sri Lanka   7.195220   79.860072       0.0       0.0
3631   2016              Sweden  58.436151   14.920181       0.0       0.0
3632   2016         Switzerland  46.204391    6.143158       0.0       0.0
3634   2016              Taiwan  25.046689  121.539533       0.0       0.0
3635   2016          Tajikistan  37.842354   70.046287       0.0       0.0
3636   2016            Tanzania  -5.168391   37.119116       0.0       0.0
3644   2016             Uruguay -32.317808  -58.076822       0.0       0.0

      counts  severe
29        12     6.0
30       468     5.0
11         3     2.0
31        33     2.0
15         1     1.0
0         21     0.0
1          1     0.0
2          1     0.0
3          1     0.0
4          6     0.0
5          2     0.0
6          1     0.0
7          2     0.0
8         12     0.0
9          1     0.0
10         3     0.0
12         4     0.0
13         5     0.0
14         1     0.0
16         3     0.0
17         2     0.0
18         9     0.0
19         1     0.0
20         2     0.0
21         2     0.0
22         1     0.0
23         1     0.0
24         1     0.0
25        10     0.0
26         4     0.0
...      ...     ...
3577       1     0.0
3579       1     0.0
3580       1     0.0
3585      15     0.0
3589       1     0.0
3593       8     0.0
3596       4     0.0
3599       1     0.0
3601       1     0.0
3603       5     0.0
3604       1     0.0
3608       6     0.0
3609       1     0.0
3613       1     0.0
3614      15     0.0
3615       3     0.0
3617       2     0.0
3620       1     0.0
3622       1     0.0
3623       1     0.0
3625      27     0.0
3626       1     0.0
3628       3     0.0
3629       1     0.0
3631      16     0.0
3632       1     0.0
3634       1     0.0
3635       1     0.0
3636       3     0.0
3644       1     0.0

[3648 rows x 8 columns]